### ISSUE TITLE
Deadlock when publishing within a subscribe callback

### ISSUE THREAD

**Issue by jhkolb** [SoftwareDefinedBuildings/bw2python#2]
It may be that a deadlock can occur when attempting to perform a publish operation within a subscription callback. This needs to be verified and, if necessary, fixed.

**Comment by immesys** [comment]
Is this specific to the python bindings? I have not observed this problem in the go bindings, but it is a "bad idea" to do this anyway because publish operations block until acknowledged by the other side, so under load you can be unsubscribed for taking too long to consume messages. It is better to decouple publishing with a queue.

**Comment by jhkolb** [comment]
This was specifically reported with respect to the Python bindings.

**Comment by gtfierro** [comment]
This is fixed in https://github.com/SoftwareDefinedBuildings/bw2python/pull/3

**Comment by jhkolb** [comment]
The fix for this was merged in as part of #3.
